# this is an file in which i can test all the routes and for this file downlod the REST client extension in vscode.

# Register
POST http://localhost:4000/register HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password123",
    "username": "johndoe"
}
###

POST http://localhost:4000/register HTTP/1.1
Content-Type: application/json

{
    "name": "moksh patel",
    "email": "mokshpatel05@gmail.com",
    "password": "password123",
    "username": "mokshpatel"
}

###

# login

POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password123"
}
###

POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
    "email": "mokshpatel05@gmail.com",
    "password": "password123"
}

###

# get user and profile

GET http://localhost:4000/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token": "a3da5c07eb0083ca0c424be42a98c7aef1bb5981ecf3bcb58c8391424f50a72b"
}

###
GET http://localhost:4000/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token": "3872ef431a90103ee68667ee1893607451986b56b2039f9c0e9601f913e1d34c"
}


###

# update profile data

POST http://localhost:4000/update_profile_data HTTP/1.1
Content-Type: application/json

{
    "token": "3872ef431a90103ee68667ee1893607451986b56b2039f9c0e9601f913e1d34c",
    "bio": "I am a software developer",
    "currentPost": "Software Developer",
    "pastWork": [
        {
            "company": "Swasemi",
            "position": "Software Developer",
            "years": "2020-2021"
        }
    ],
    "education": [
        {
            "school": "LJ University",
            "degree": "Bachelor of Science",
            "fieldOfStudy": "Computer Science",
            "years": "2016-2020"
        }
    ]
}

###

# get all users profile

GET http://localhost:4000/user/get_all_users_profiles HTTP/1.1
Content-Type: application/json

###

GET http://localhost:4000/posts HTTP/1.1
Content-Type: application/json